import {
  agenticBenchmarkAcquisitionReplayResultJsonSchema,
  agenticBenchmarkAcquisitionRequestJsonSchema,
  agenticBenchmarkAcquisitionResultJsonSchema,
  agenticBenchmarkArtifactJsonSchema,
  agenticBenchmarkReplayResultJsonSchema,
  agenticBenchmarkRequestJsonSchema,
  agenticCorpusAllocationJsonSchema,
  agenticCorpusAllocationCommitmentJsonSchema,
  agenticCorpusAllocationCommitmentReplayResultJsonSchema,
  agenticCorpusAllocationReplayResultJsonSchema,
  agenticCorpusAllocationRevealJsonSchema,
  agenticCorpusAllocationRequestJsonSchema,
  agenticCorpusExperimentArtifactJsonSchema,
  agenticCorpusExperimentPlanJsonSchema,
  agenticCorpusExperimentPlanReplayResultJsonSchema,
  agenticCorpusExperimentReplayRequestJsonSchema,
  agenticCorpusExperimentReplayResultJsonSchema,
  agenticCorpusExperimentRequestJsonSchema,
  agenticCorpusProvenanceJsonSchema,
  agenticCorpusTrustPolicyJsonSchema,
  agenticProfileReplayResultJsonSchema,
  agenticProfileReplayResultV2JsonSchema,
  agenticProfileReportJsonSchema,
  agenticProfileReportV2JsonSchema,
  agenticProfileRequestJsonSchema,
  agenticProfileRequestV2JsonSchema,
  evidenceManifestJsonSchema,
  replayResultJsonSchema,
  repositoryAnalysisJsonSchema,
  repositoryAuditJsonSchema,
  repositoryInitConfigJsonSchema,
  repositoryInitLockJsonSchema,
  repositoryInitResultJsonSchema,
  verificationRequestJsonSchema,
} from "../src/contracts/index.js";

export function publishedSchemas(): ReadonlyArray<readonly [string, Record<string, unknown>]> {
  return [
    ["agentic-corpus-trust-policy.v1.json", agenticCorpusTrustPolicyJsonSchema()],
    ["agentic-corpus-provenance.v1.json", agenticCorpusProvenanceJsonSchema()],
    ["agentic-benchmark-request.v1.json", agenticBenchmarkRequestJsonSchema()],
    ["agentic-benchmark-artifact.v1.json", agenticBenchmarkArtifactJsonSchema()],
    ["agentic-benchmark-replay-result.v1.json", agenticBenchmarkReplayResultJsonSchema()],
    [
      "agentic-benchmark-acquisition-request.v1.json",
      agenticBenchmarkAcquisitionRequestJsonSchema(),
    ],
    ["agentic-benchmark-acquisition-result.v1.json", agenticBenchmarkAcquisitionResultJsonSchema()],
    [
      "agentic-benchmark-acquisition-replay-result.v1.json",
      agenticBenchmarkAcquisitionReplayResultJsonSchema(),
    ],
    ["agentic-profile-request.v1.json", agenticProfileRequestJsonSchema()],
    ["agentic-profile-report.v1.json", agenticProfileReportJsonSchema()],
    ["agentic-profile-replay-result.v1.json", agenticProfileReplayResultJsonSchema()],
    ["agentic-profile-request.v2.json", agenticProfileRequestV2JsonSchema()],
    ["agentic-profile-report.v2.json", agenticProfileReportV2JsonSchema()],
    ["agentic-profile-replay-result.v2.json", agenticProfileReplayResultV2JsonSchema()],
    ["verification-request.v1.json", verificationRequestJsonSchema()],
    ["repository-analysis.v1.json", repositoryAnalysisJsonSchema()],
    ["repository-audit.v1.json", repositoryAuditJsonSchema()],
    ["repository-init-config.v1.json", repositoryInitConfigJsonSchema()],
    ["repository-init-lock.v1.json", repositoryInitLockJsonSchema()],
    ["repository-init-result.v1.json", repositoryInitResultJsonSchema()],
    ["evidence-manifest.v1.json", evidenceManifestJsonSchema()],
    ["replay-result.v1.json", replayResultJsonSchema()],
    ["agentic-corpus-allocation-request.v1.json", agenticCorpusAllocationRequestJsonSchema()],
    ["agentic-corpus-allocation.v1.json", agenticCorpusAllocationJsonSchema()],
    [
      "agentic-corpus-allocation-replay-result.v1.json",
      agenticCorpusAllocationReplayResultJsonSchema(),
    ],
    ["agentic-corpus-allocation-commitment.v1.json", agenticCorpusAllocationCommitmentJsonSchema()],
    ["agentic-corpus-allocation-reveal.v1.json", agenticCorpusAllocationRevealJsonSchema()],
    [
      "agentic-corpus-allocation-commitment-replay-result.v1.json",
      agenticCorpusAllocationCommitmentReplayResultJsonSchema(),
    ],
    ["agentic-corpus-experiment-plan.v1.json", agenticCorpusExperimentPlanJsonSchema()],
    [
      "agentic-corpus-experiment-plan-replay-result.v1.json",
      agenticCorpusExperimentPlanReplayResultJsonSchema(),
    ],
    ["agentic-corpus-experiment-request.v1.json", agenticCorpusExperimentRequestJsonSchema()],
    ["agentic-corpus-experiment-artifact.v1.json", agenticCorpusExperimentArtifactJsonSchema()],
    [
      "agentic-corpus-experiment-replay-request.v1.json",
      agenticCorpusExperimentReplayRequestJsonSchema(),
    ],
    [
      "agentic-corpus-experiment-replay-result.v1.json",
      agenticCorpusExperimentReplayResultJsonSchema(),
    ],
  ];
}
